apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: slate-nginx
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: slate-nginx
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: slate-nginx-configmap
